name: release
on: 
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    env :
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js And Setup .npmrc
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope       : 'tf0101'
          always-auth : true
      - name: Can Publish
        run : npx can-npm-publish --verbose
      - name: Install
        run : npm install
      - name: Build
        run : npm run build-bundle
      - name: Publish
        run : npm publish